apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc
  namespace: task01
spec:
  type: ClusterIP
  selector:
    app: nginx-multitool
  ports:
    - name: http
      port: 9001
      targetPort: 80
      protocol: TCP
    - name: multitool
      port: 9002
      targetPort: 8080
      protocol: TCP
