apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  namespace: task01
spec:
  selector:
    app: nginx-multitool
  type: NodePort
  ports:
    - name: http
      port: 9001          # куда стучится клиент (ClusterIP / DNS)
      targetPort: 80      # nginx в контейнере
      protocol: TCP
    - name: multitool
      port: 9002
      targetPort: 8080    # multitool в контейнере
      protocol: TCP
